# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://arya-araban.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: arya-araban.github.io

# Title of the Site
title: Arya Araban
# Description of the Site
description: Computer Engineer, Specializing in Artificial Intelligence 
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "/assets/images/backgrounds/home-bg-2.jpg"
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: arya.araban21@gmail.com
facebook_username: arya.araban
instagram_username: arya_a211
telegram_id: arya_araban
linkedin_username: arya-araban
github_username:  arya-araban
discord_id: "713688222584012830"
reddit_username: arya_a211
btc_address: bc1qtyfg45ynxzwkyuww2pxdmfgdrtf4zef6l6jkl8
# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Arya Araban
# URL for the Image of the Author
author-image: "/assets/images/profile.jpg"
# Many Words About the Author
author-about: Hey there! I'm Arya. I'm a 23 year old computer engineering graduate. My main interests consist of Artifical Intelligence, Computer Vision, and web development. I enjoy working out, outdoor activities, and reading in my free time. <br><br> You can check out my resume by clicking the link below!
#short description about the author 
short-about: Computer Engineering Graduate @ FUM. AI Engineer, Web Developer
#path to CV 
resume: "/assets/files/resume.pdf"

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/arya-araban

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
